version: '3.1'
services:
  db:
    image: zecure/shadowd_database
    restart: always
    volumes:
      - "${SHADOWD_DB_LOCATION}:/var/lib/postgresql/data"
    env_file:
      - "${SHADOWD_ENV_DB_LOCATION}"

  web:
    image: zecure/shadowd_ui
    restart: always
    ports:
      - 8080:80
    links:
      - db
    depends_on:
      - db
    env_file:
      - "${SHADOWD_ENV_DB_LOCATION}"

  shadowd:
    image: zecure/shadowd
    restart: always
    ports:
      - 9115:9115
    links:
      - db
    depends_on:
      - db
    env_file:
      - "${SHADOWD_ENV_DB_LOCATION}"

